version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped
