services:
  - type: web
    name: skillexchange-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_JWT_EXPIRES_IN
        value: 1d
      - key: CORS_ORIGIN
        value: "https://skillexchange-su69.onrender.com,https://skill-exchange-blush.vercel.app,https://skillexchange.vercel.app"
      - key: CORS_CREDENTIALS
        value: "true"
